package edu.fmi.genderclassify.dataimport;

public enum ExtraFields {
    TWEET_COORDINATES_LATITUDE,
    TWEET_COORDINATES_LONGITUDE,
    TWEET_MALE_FEMALE_WORDS_SCORE,
    DESCRIPTION_MALE_FEMALE_WORDS_SCORE
}
